### PR TITLE
Revamp recent activity.

### PR DESCRIPTION
**Pull request by mattbk**
Part of https://github.com/liberapay/liberapay.com/issues/788.

Try number two...

Not sure if there is a way to just run one query, feedback appreciated.

### CODE REVIEW

**Comment by mattbk** [comment]
image

- [ ] pull out most recent users into a separate line? Don't duplicate.
- [ ] should be monthly funding for month stats, not weekly (query looks right, text is wrong)
    - [ ] also for pledges
- [ ] flip week and month position (week first)
- [ ] rename monthly query

**Comment by Changaco** [comment]
I think showing both past-week and past-month numbers at the same time is too much. A bit of JavaScript to allow the user to switch between the two time frames would be nicer. But really I'm not sure this kind of thing belongs on the front page, I don't see it being used by more than a small minority of visitors. I also don't think that this actually fixes #788 because your original message was mostly about being able to explore the recent activity.

**Comment by mattbk** [comment]
Can I build it into an admin page?

**Comment by Changaco** [comment]
Sure, feel free to build lots of admin tools, we need more of them.

**Pull request closed without merging**
