### PR TITLE
Homepage pitch

### PR DESCRIPTION
**Pull request by Changaco**
This PR modifies the homepage in an attempt to make Liberapay more appealing to visitors who aren't already excited about it. I need some feedback on this. Here's a screenshot of the top:

liberapay-2016-02-15-homepage-pitch

And here's the "Upcoming Features" section:

spectacle fvs819

### CODE REVIEW

**Comment by MartinDelille** [comment]
:+1: 
Maybe make the icon a little bit bigger?

**Comment by Changaco** [comment]
Icon size increased.

**Comment by Changaco** [comment]
Now let's get this translated into French before deploying.

**Comment by Changaco** [comment]
Translation done, new version deployed. :-)

**Pull request merged**
