### PR TITLE
Automatic renewals

### PR DESCRIPTION
**Pull request by Changaco**
Today is the fourth anniversary of Liberapay's launch, and I've been trying to finish implementing #483 so that we can announce this new feature in our annual blog post. It's very late but I finally have an implementation that should (mostly) work, so we may be able to pull that off.

### CODE REVIEW

**Comment by trebmuh** [comment]
Very nice to see this feature coming in!

**Comment by Changaco** [comment]
I've merged this and pushed the new strings to Weblate so that translators can start working.

**Comment by trebmuh** [comment]
Awesome.
I made half of the French translation.
Will probably do the other half tomorrow.

**Comment by trebmuh** [comment]
Done, French translation is back to 100% now.

**Comment by Changaco** [comment]
I've deployed this and run the `schedule_renewals` function for almost every donor. There are now 5364 scheduled payments.

**Pull request merged**
