### PR TITLE
Remove .lfsconfig fix #397

### LINKED ISSUE #397: Error when checking out the source
I tried a fresh clone without success:

```
$ git clone git@github.com:liberapay/liberapay.com.git
Cloning into 'liberapay.com'...
remote: Counting objects: 54058, done.
remote: Total 54058 (delta 0), reused 0 (delta 0), pack-reused 54058
Receiving objects: 100% (54058/54058), 24.21 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (36427/36427), done.
Checking connectivity... done.
Downloading www/assets/mangopay/Mangopay_Terms-AT.pdf (819.09 KB)
Error downloading object: www/assets/mangopay/Mangopay_Terms-AT.pdf (4bd21269a96fa217ec75452fed617c50b5d66ba99d83743baabcbd9c9b896638)

Errors logged to /Users/martin/dev/Liberapay/temp/liberapay.com/.git/lfs/objects/logs/20160816T024548.029415249.log
Use `git lfs logs last` to view the log.
error: external filter git lfs smudge %f failed 2
error: external filter git lfs smudge %f failed
fatal: www/assets/mangopay/Mangopay_Terms-AT.pdf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

I tried several workaround explained [here](https://github.com/github/git-lfs/issues/911) without success.

### PR DESCRIPTION
**Pull request by MartinDelille**

### CODE REVIEW

**Comment by Changaco** [comment]
There's a reason we have this file, [git-lfs-fetch.py](https://github.com/liberapay/git-lfs-fetch.py) needs it on the production server to know where the LFS endpoint is.

**Comment by MartinDelille** [comment]
I followed @jhosman advice:

> If you really need to SSH for LFS instead of Git, please run this command:
> git config --file=.lfsconfig lfs.url git@github.com:liberapay/liberapay.com

**Comment by Changaco** [comment]
Okay, we just need to check that [git-lfs-fetch.py](https://github.com/liberapay/git-lfs-fetch.py) will still work or modify it if not.

**Comment by MartinDelille** [comment]
How can I do that?

**Comment by Changaco** [comment]
I did it myself. I ran `python -m git_lfs -vv liberapay.com.git/.git liberapay.com-fix-lfs` (the latter directory being unpacked from [an archive of the current branch](https://codeload.github.com/liberapay/liberapay.com/zip/fix-lfs)). It failed, so I [updated](https://github.com/liberapay/git-lfs-fetch.py/commit/b0c0d6f91fab8e622a5275a7927aa28b3201a860) git-lfs-fetch.py.

**Pull request merged**
