### PR TITLE
Light accounts

### LINKED ISSUE #247: Donate without account
I just had a donee who complaint about him having to register an account. It'd be neat to support those recurring paypal transactions or something like that without account, not sure how that works though.

### PR DESCRIPTION
**Pull request by Changaco**
This PR simplifies the account creation form by removing the username and password fields. It's meant to close #247.

### CODE REVIEW

**Comment by Changaco** [comment]
Suggestions and criticisms welcome.

**Comment by Changaco** [comment]
Nobody? :cry:

**Comment by revi** [comment]
As long as users can decide their username (and it seems they can) I think it's good.

**Comment by Changaco** [comment]
Thank you for breaking the silence @revi! :-)

Yes, it's still possible to set a username, the input has just moved from the sign-up form to the Profile Edit page.

**Pull request merged**
