### PR TITLE
Integrate Bootstrap

### PR DESCRIPTION
**Pull request by Changaco**
This PR is to unblock #183, it allows customizing Bootstrap by modifying the new `style/variables.scss` file. Ping @MartinDelille and @Calinou.

### CODE REVIEW

**Comment by Changaco** [comment]
TODO:

- [ ] fix the tests
- [ ] update the CSS section of the README

**Comment by Changaco** [comment]
Coincidentally, [Bootstrap 3.3.7 has just been released](http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/), so we should upgrade before merging this.

**Comment by MartinDelille** [comment]
This is awesome and will help us make it look nice :-)

Just a question: why not using git submodule to link bootstrap code?

**Comment by Changaco** [comment]
> Just a question: why not using git submodule to link bootstrap code?

It didn't come to mind because I never use them and they have a bad reputation, but I guess we could try.

**Comment by MartinDelille** [comment]
It is not a big deal when you use it for external projects. A lot of bug have been fixed also. After that I think bower.io is also a simple solution for referencing external code (simpler to use than git submodule). Any preference?

**Comment by Changaco** [comment]
No Bower. Preferred solutions:

1. git submodule if it's not a pain in the ass
2. a tarball stored with git-lfs and unpacked at the appropriate time
3. just leave things as they are now

**Comment by MartinDelille** [comment]
Let's go with 3, but using submodule afterward will make handling upgrade easier.

**Comment by Changaco** [comment]
We can make it easy to upgrade no matter which option we choose.

**Comment by MartinDelille** [comment]
Maybe, but using submodule reduce the codebase and the diff. Although it is always possible to patch a vendor code by forking it and referencing the fork in the submodule.

**Comment by Changaco** [comment]
Option 2 (using a tarball and git-lfs) has the same advantages, only option 3 (storing the files directly in our git) generates diff noise.

**Comment by MartinDelille** [comment]
You're right. I never used git-lfs yet.

**Comment by Changaco** [comment]
I explored the possibilities of using git-lfs for this, but if we did that then we'd have to add git-lfs as a required dependency (right now it's only used for the PDFs of MangoPay's terms, so it's optional).

**Comment by Changaco** [comment]
Deploying this broke everything because `libsass` failed to compile with the obsolete version of `gcc` present on the server.

**Comment by Changaco** [comment]
Upstream has a pull request to bring back compatibility with older GCC versions, https://github.com/sass/libsass/pull/1623, but we can't wait for that.

**Comment by Changaco** [comment]
The libsass python package actually provides binaries. `pip` wasn't using them because it was also out-of-date. After upgrading pip, installing an up-to-date precompiled version of libsass succeeded, and re-deploying version 126 of liberapay worked.

**Comment by MartinDelille** [comment]
Regarding the submodule option, usually, I create a vendor directory in the root directory. Do you prefer me to keep the current architecture and I will have to find how to make a submodule that point to a repository subdirectory (https://github.com/twbs/bootstrap-sass/tree/master/assets/stylesheets).

What do you prefer? If you think it is a waste of time, tell me.

**Comment by Changaco** [comment]
There's no point in changing the integration now, we went with option 3 (directly including the Bootstrap source in our git), let's stick with it until we have a good reason to switch to something else.

**Pull request merged**
