### PR TITLE
Improve sign in flow

### LINKED ISSUE #445: Logging in has become more difficult
In #421 I optimized the sign-in template for new users, putting the sign-up form on top. This results in the sign-in page (<https://liberapay.com/sign-in>) impeding users that are simply trying to log in.

The solution is simple: use two separate templates.

### PR DESCRIPTION
**Pull request by Changaco**
Closes #445.

### CODE REVIEW

**Comment by Changaco** [comment]
Before:

liberapay-2017-01-02-account-closed-before

After:

liberapay-2017-01-02-account-closed

**Comment by Changaco** [comment]
I'd appreciate feedback on the change from "Sign In" to "Log In or Create Account" for the navbar link (see top-right of screenshots). It's inspired by <https://github.com/liberapay/liberapay.com/issues/445#issuecomment-269897806>.

**Comment by EdOverflow** [comment]
"Log In or Create Account" is definitely clearer. If you want to improve the usability of Liberapay I would highly recommend watching the following video: [The User is Drunk](https://www.youtube.com/watch?v=r2CbbBLVaPk).

**Comment by Changaco** [comment]
@EdOverflow Thanks for the feedback. :-)

**Pull request merged**
