### PR TITLE
Attempt to clarify the "Receiving" page a little

### LINKED ISSUE #1197: Receiving page information are confusing
Related to: https://mastodon.xyz/@Liberapay/100520158923864989
Translation for the non-French readers:
> @Liberapay and otherwise, clarifying this mess would be possible???
> You need a stripe account to receive but not to give on one side, on another side it tells me that I'm still receiving????
> and from another side I can't give?
> and that, in fact, according to the logs, that... works?

***

On [my account](https://liberapay.com/me/receiving/), I've got this:

liberapay-flou

First line says that I'm receiving some money, second line says I can't receive money. It is confusing and needs to be clarified.

I'm trying a shot in the dark since I'm not totally sure how LP works nowadays (I'm still catching up  after 4 weeks of-the-web with what changed in LP):
- **First line**: You're receiving €XX.XX from donors per week.
- **Second line**: You can't transfer the money from your LiberaPay account to your bank account until you've configured a payment account.

@Changaco can you please confirm/infirm that my shot in the dark is right/wrong?

### PR DESCRIPTION
**Pull request by Changaco**
This branch fixes #1197 (I hope). As always, feedback is welcome.

### CODE REVIEW

**Comment by Changaco** [comment]
Ping @mattbk and @trebmuh. Is the new wording better?

**Comment by trebmuh** [comment]
Should be good :+1:

**Comment by mattbk** [comment]
I think this is fine.

**Comment by Changaco** [comment]
After noticing that the number of donors displayed was wrong (fixed in 6e6024d0d0efaea508746bd6b640b1589785c024), I've realized that we should distinguish between personal patrons and team patrons in the "Receiving" page. I've noted this idea in the next branch so I won't forget.

**Pull request merged**
