### PR TITLE
 Add visibility of giving and receiving

### PR DESCRIPTION
**Pull request by oliverpool**
Related to https://github.com/liberapay/liberapay.com/issues/800.

This adds a link near the text `You give/receive {amount} per week` mentioning the visibility (`public` or `secret`), with a link to the settings page (to eventually change it).

---
2017-11-20-153509_2560x1080_scrot

---
2017-11-20-153605_2560x1080_scrot

---

This is my first actual contribution to liberapay, so please feel free to point out my mistakes or where I could improve the code (especially regarding how the translation should be handled)

### CODE REVIEW

**Comment by Changaco** [comment]
I'm not convinced by the proposed UI change, I think it's distracting and potentially confusing. What are you trying to accomplish by directing the user's attention to the privacy settings?

**Comment by oliverpool** [comment]
I think I misread the issue #800 and thought that you were talking about the anonymity of the amount given/received (when you actually meant that your benefactors are anonymous).

Anyway, I think it is important to mention to the user if the amount they receive/give is secret or public (the link is there just to show the user that they can control this visibility parameter)

**Comment by whit537** [comment]
Would this look better?

> You [publicly]() receive €0.00 per week.
> You [secretly]() give €0.00 per week.

I agree the UI could be improved but tbh that's somewhat true across the board. Not sure this change actively degrades the existing experience.

**Comment by Changaco** [comment]
I remain unconvinced and I think a single word isn't clear enough, especially in the long run with the possibility of non-anonymous donations (#271). Something like "(This information is public.)" might work.

**Comment by oliverpool** [comment]
> especially in the long run with the possibility of non-anonymous donations

Then maybe a specific "is public"-icon would be nice to quickly know if an information is public (I would personally assume that everything that isn't explicitly marked as "public" is "private/secret").

What do you think of the [bullhorn](http://fontawesome.io/icon/bullhorn/)? :smile:

**Comment by MartinDelille** [comment]
@oliverpool The bullhorn evocate a notification. For mem the icon indicating that an information is public is the [earth](https://fontawesome.com/icons/globe-africa?style=solid) (maybe because I use facebook a lot).

**Pull request closed without merging**
