### PR TITLE
Add telegram channel

### PR DESCRIPTION
**Pull request by MartinDelille**
Telegram is a nice way to broadcast information. The current channel is empty so I hesitating between posting all medium article or just the last one.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Is anything blocking this pull request?

**Comment by Changaco** [comment]
1. This branch is incomplete, it doesn't update the `/about/contact` page.
2. I don't see any reason to start using Telegram and adopt it for Liberapay.

**Comment by MartinDelille** [comment]
I just pushed something on the about/contact page without checking (problem with my dev environment #1237).

Concerning using telegram, I created the channel and the group and people are on it (and having a discussion):
- https://t.me/liberapay
- https://t.me/joinchat/HZKyvg8F5-ncY5c1ukzDbA

The question is more: why not using Telegram?

**Comment by MartinDelille** [comment]
Here is a preview of the footer:

Screenshot 2019-03-17 21 23 26

And from the contact form:

Screenshot 2019-03-17 21 45 57

**Comment by MartinDelille** [comment]
Here is also a screenshot of the Telegram channel sharing all the Medium post:

Screenshot 2019-03-17 21 48 14

As you can see the last post had quite a lot of view (126) even if it is not advertised on the website.

**Comment by MartinDelille** [comment]
I solved locally the conflicts.

**Pull request closed without merging**
