### PR TITLE
Add FUNDING.yml

### PR DESCRIPTION
**Pull request by revi**
GitHub support Liberapay for the [sponsor stuff](https://tppr.me/bHFOr), so it's obviously natural to make use of the stuff for dogfooding on our own.

### CODE REVIEW

**Comment by revi** [comment]
You will have to enable "Sponsorships" on the Settings to see this in action after merging this.

image

**Comment by jorgesumle** [comment]
I've already enabled the setting, but to keep it simple just add what we need to the file. 

```
liberapay: Liberapay
```

When done, it can be merged.

**Comment by revi** [comment]
@jorgesumle Done! :)

**Comment by jorgesumle** [comment]
@Changaco, I merged it just a while ago locally and pushed just at the same time (https://github.com/liberapay/liberapay.com/commit/68535188b1f35a321a43c35f647e14ee6fdf9e97) you pushed the last fix, so I can close it now. :)

**Comment by Changaco** [comment]
@jorgesumle Next time please merge through GitHub.

**Pull request closed without merging**
