### PR TITLE
Create a security.txt file.

### PR DESCRIPTION
**Pull request by EdOverflow**
This commit adds a security.txt file under the `.well-known` directory of liberapay.com. The file consists of a `Contact:` and `Acknowledgments:` directive that point to Liberapay's HackerOne program.

### CODE REVIEW

**Comment by Changaco** [comment]
This doesn't work yet. The version of Aspen we're using still rejects all requests for "hidden" paths, even `.well-known`.

**Comment by EdOverflow** [comment]
I had a feeling that would be the case, @Changaco. Any pointers on where in Aspen I could resolve this?

**Comment by Changaco** [comment]
The only clean way to resolve this is to modify Pando to use the latest version of Aspen (1.0rc4). I have a branch for that and I'm looking to see if I can complete it today.

**Comment by mattbk** [comment]
> This doesn't work yet.

You know, I had a feeling when I reviewed that I would be proven wrong. I need to trust that more.

**Pull request merged**
