### PR TITLE
Revamp the subnavs

### PR DESCRIPTION
**Pull request by Changaco**
This branch replaces the horizontal tabs present in many pages with vertical navs. It also adds links to facilitate switching between a personal settings page and a team settings page.

### CODE REVIEW

**Comment by Changaco** [comment]
Here are some screenshots at 1024x768:

Screenshot of the "Explore Teams" page

Screenshot of the "Explore Organizations" page

---

Screenshot of the "About" page

Screenshot of the "FAQ" page

Screenshot of the "Global" page

---

Screenshot of an "Edit Username" page

Screenshot of a "Giving" page

Screenshot of a "Ledger" page

Screenshot of an "Account" page

Screenshot of an "Admin" page

**Comment by trebmuh** [comment]
:-1:

**Comment by Changaco** [comment]
To clarify, this is needed because horizontal tabs don't scale well. If there are many tabs and the viewer's screen isn't wide enough, then the tabs overflow in an ugly way, and I don't know of a way to fix that without using JavaScript. Moreover tabs only allow one level, so it's difficult to properly include subpages. Finally, on wide screens it's better to have sidebars that horizontal tabs, because vertical space is limited.

**Comment by Changaco** [comment]
To illustrate the overflow problem, here's a screenshot of https://eo.liberapay.com/about/ at the same resolution of 1024x768:

Screenshot of the current "About" page in Esperanto

**Pull request merged**
