### PR TITLE
Improve handling of complex plurals

### PR DESCRIPTION
**Pull request by Changaco**
See <https://github.com/liberapay/salon/issues/125#issuecomment-329496197>.

### CODE REVIEW

**Comment by Changaco** [comment]
I've opened an issue upstream: <https://github.com/python-babel/babel/issues/530>.

**Comment by Changaco** [comment]
Sneaked in a commit to take care of #696.

**Comment by trebmuh** [comment]
:+1:

**Comment by Changaco** [comment]
@pskosinski finds this confusing.

**Comment by pskosinski** [comment]
Now, after reading discussion starting here https://github.com/liberapay/salon/issues/125#issuecomment-329496197 I do understand what's going on. Although, when I visited Weblate to check if anything needs translating, noticed all the failed tests and `<unused singular (hash=…` as source strings I thought something in the Liberapay's or Weblate's source code got broken. It was not intuitive to me. Now it seems like a good solution though, I guess.

**Comment by pskosinski** [comment]
Seems like the strings whose msgid's got converted, e.g.:
```
-msgid "Your donations will be funded for {n} weeks ({0})"
+msgid "<unused singular (hash=578803aaecf90d69fa606ab0f5a693e9)>"
```
stay untranslated on the website, even that they are translated on the Weblate. It's easiest to notice if you switch language to a fully translated language (e.g. French, German) and scroll down to "Recent activity" section. All the strings there are in English, even that they were getting replaced with their translations some time ago.

**Comment by Changaco** [comment]
/o\

Working on a fix…

**Comment by Skybladev2** [comment]
@Changaco Can you please clarify when this fix will be reflected to Weblate?
I see this at the moment:

default

**Comment by Changaco** [comment]
@Skybladev2 I'm not sure what you were asking, but your comment made me realize that the source string in your screenshot was wrong because we do use the singular. I've fixed it in b29b73b2cf4705553a44224ba6bfb42fa1c53c69.

**Comment by Skybladev2** [comment]
@Changaco I see several errors in source strings, you can see it by following this link: https://hosted.weblate.org/translate/liberapay/core/ru/?type=check%3Apython_brace_format&offset=0

Is it Weblate issue or Liberapay issue?

**Comment by Changaco** [comment]
The source strings are exactly what they're supposed to be. Weblate's warnings and errors are about the differences between the singular source string and its translation, they can be dismissed.

**Pull request merged**
