### PR TITLE
Redesign the "Giving" page

### LINKED ISSUE #985: Human readable N=X
On the giving page the Donations, Pledges and Recently Cancelled topic have N=X in there title. For non-programmers and non-technical people this may look a bit weird. My suggestion is to change it to just X. So:

Donations (N=8) -> Donations (8)
Pledges (N=8) -> Pledges (8)
Recently Cancelled (N=8) -> Recently Cancelled (8)

### PR DESCRIPTION
**Pull request by Changaco**
- make the page responsive (fixes the first item of #514)
- show when the next payment is due for each donation
- provide a way out of #1250 by adding a "Renew" button for each donation awaiting payment
- fix #985 by removing the 3 "N=" from section titles

### CODE REVIEW

**Comment by Changaco** [comment]
# Screenshots

## Wide
screenshot_20180928_185312

## Narrow

liberapay-2018-09-28-giving-page-xs

**Comment by trebmuh** [comment]
Very nice :+1:

**Comment by trebmuh** [comment]
Very nice looking :+1:

**Comment by Changaco** [comment]
# Screenshots before

## Wide

screenshot_20180928_185941

## Narrow (partial due to overflow)

liberapay-2018-09-28-old-giving-page-xs-1
liberapay-2018-09-28-old-giving-page-xs-2

**Pull request merged**
