### PR TITLE
Mangopay exodus notification

### PR DESCRIPTION
**Pull request by Changaco**
WIP, feedback welcome.

### CODE REVIEW

**Comment by LiamDawe** [comment]
Spelling error:

> recommanded

Should be recommended.

Other than that, it seems okay.

**Comment by Changaco** [comment]
Thanks @LiamDawe.

**Comment by Changaco** [comment]
I'm merging this now to give translators some time to do their work while I figure out how I'm going to proceed to actually send these notifications.

**Comment by jorgesumle** [comment]
>  If you get an error message like “The attempt to distribute all the money in your wallet failed: XX.XX remains.” then the problem is probably on the recipient side 

It should read "If you get an error message like “The attempt to distribute all the money in your wallet failed: XX.XX remains.”**,** then the problem is probably on the recipient side"

> If you use Liberapay as a donor the first choice is recommended

It should read "If you use Liberapay as a donor**,** the first choice is recommended"

As of https://github.com/liberapay/liberapay.com/issues/959, I'd recommend not writing conditional sentences without comma. They are very difficult to read, incorrect and I always end up adding commas in the translation.

**Comment by jorgesumle** [comment]
> You can find more information in {link3_start}this blog post{link_end}, and as always you can reply to this email if you need help.

The linked blog post from one of our strings is only in English, so translators should specify that it's only in English, but how can they know?

This is related to https://github.com/liberapay/salon/issues/136

**Comment by Changaco** [comment]
I've just sent a first wave to 513 recipients.

```python
>>> from liberapay.main import *
Won't log to Sentry (SENTRY_DSN is empty).
>>> langs = set('nl fi es pt uk ru ms nb zh fr en'.split())
>>> recipients = website.db.all("select p from participants p where balance > 0 and is_suspended is not true and exists (select 1 from transfers t where t.tippee = p.id)")
>>> len(recipients)
593
>>> len([1 for p in recipients if p.email_lang not in langs])
80
>>> sent = 0
>>> for p in recipients:                                   
...   if p.email_lang in langs:
...      p.notify('once/mangopay-exodus', force_email=True, type='warning')
...      sent += 1
... 
>>> sent
513
```

**Comment by Changaco** [comment]
An Italian translation has been added. German is still missing.

**Comment by Changaco** [comment]
I've just sent the final wave: 357 emails.

**Pull request merged**
