### PR TITLE
Jinja line statements

### LINKED ISSUE #52: Switch Jinja templates to line statements
Because they're easier to type (especially on an azerty keyboard): `% if ...` instead of `{% if ... %}`. [Documentation](http://jinja.pocoo.org/docs/dev/templates/#line-statements).

Any objections?

### PR DESCRIPTION
**Pull request by Changaco**
Closes #52. Please take a look and tell me if this change looks okay to you.

### CODE REVIEW

**Comment by Changaco** [comment]
@rohitpaulk May I have your opinion? If this PR was for Gratipay would you approve it?

**Comment by techtonik** [comment]
What about IDEs support for this Jinja syntax?

**Comment by Changaco** [comment]
@techtonik I don't know, I don't use IDEs, but if an editor wants to support highlighting templates markup in HTML files then it should make the syntax configurable.

**Comment by rohitpaulk** [comment]
I personally wouldn't prefer the line statement syntax in HTML files - the file structure ends up looking inconsistent. However, I'd support a complete change to something like [HAML (ruby)](http://haml.info/tutorial.html) (https://github.com/Rootbuzz/shpaml, maybe?) 

 The PR in itself looks good though :)

**Comment by Changaco** [comment]
I agree that it looks inconsistent, but let's go with it anyway while we consider better solutions in #80.

**Comment by Changaco** [comment]
!m @rohitpaulk @techtonik

**Comment by Changaco** [comment]
This PR also activated Jinja's line comments, but they were breaking templates and we weren't using them, so I deactivated them in 1ee1e48fdad3099f4ac33c9dd7f3bbb26de62333.

**Pull request merged**
