### PR TITLE
Update pledges confirmation text

### PR DESCRIPTION
**Pull request by subkrish**
Issue #597 

This PR updates the pledges confirmation text.

### CODE REVIEW

**Comment by subkrish** [comment]
@Changaco Please have a look at the change.

**Comment by Changaco** [comment]
I think it would be better to have separate messages for pledges instead of replacing the messages for donations. (After rereading the original issue I realize it wasn't clearly stated.)

You can check `out['is_pledge']` to determine which message to use.

**Comment by subkrish** [comment]
@Changaco Ohh. So are you saying I check for it and then if its that situation -> `out['is_pledge']` then print the messages suggested in the issue?

**Comment by Changaco** [comment]
1) rename the `MESSAGES` constant to `DONATION_MESSAGES`

2) add a new `PLEDGE_MESSAGES` dict (I suggest using "You have now pledged to donate …" instead of "You have now pledged donating …")

3) replace

```python
msg = MESSAGES[out['period']]
```

with

```python
messages = PLEDGE_MESSAGES if out['is_pledge'] else DONATION_MESSAGES
msg = messages[out['period']]
```

**Comment by subkrish** [comment]
@Changaco Changed it. Thanks!

**Comment by Changaco** [comment]
Travis is green, merging.

**Comment by Changaco** [comment]
@subkrish Congrats on your first PR merged in Liberapay. :-)

**Pull request merged**
