### PR TITLE
Implement SEPA Direct Debits through Stripe

### LINKED ISSUE #1233: SEPA Direct Debits
Stripe has enabled SEPA Direct Debits on our account, we need to finish the implementation on our side.

### PR DESCRIPTION
**Pull request by Changaco**
This PR will close #1233.

### CODE REVIEW

**Comment by Changaco** [comment]
Any feedback on wording? Don't wait until the new strings have been merged and translated to suggest improvements.

**Comment by Changaco** [comment]
Screenshot of the payment method selection page

**Comment by Changaco** [comment]
Screenshot of a direct debit payment form

**Comment by Changaco** [comment]
Note: there are [official translations for the mandate text](https://www.europeanpaymentscouncil.eu/other/core-sdd-mandate-translations). I'll have to copy-paste them manually.

**Comment by trebmuh** [comment]
> Any feedback on wording? Don't wait until the new strings have been merged and translated to suggest improvements.

LGTM :+1:

**Pull request merged**
