### PR TITLE
Transform the payday income notification

### LINKED ISSUE #1188: Payouts are messed up
Got an email saying:

> €28.45 was given to you personally.

Only 4.31 has ended up in my wallet? 

Also had a [report](https://twitter.com/HerrMuskat/status/1021804807408037890) that a user was unable to empty their remaining funds to me.

My receiving page says:

> You receive €28.20 per week.
> You can't receive money until you've configured a payment account.

I'm assuming something has messed up, with the move away from Mangopay.

### PR DESCRIPTION
**Pull request by Changaco**
This branch attempts to fix #1188. Feedback welcome.

### CODE REVIEW

**Comment by LiamDawe** [comment]
So is Mangopay still actually live?

I'm confused, since my account still says I'm getting a weekly amount, but I don't use Stripe.

**Comment by Changaco** [comment]
The Mangopay part only appears if there is money in the wallet, it's just a reminder to withdraw.

**Comment by LiamDawe** [comment]
Right, so Mangopay is still actually live?

I added Stripe as a payment method, but I think that's only for paying others right? I assume Mangopay is still what's currently used to withdraw money? All a bit confusing, especially since there's been no announcements or blog posts to update creators on what's actually happening currently.

Please improve communication.

**Comment by mattbk** [comment]
Stripe is for receiving payments, but is not live at the moment.

**Comment by LiamDawe** [comment]
Interesting, was I supposed to get some kind of email from Stripe when i attached it to Liberapay? The sign up form it links was easy enough to do and it seems to have worked, but Stripe didn't send me any confirmation.

**Comment by mattbk** [comment]
The way I understand it right now (will edit if @Changaco tells me I'm wrong):

- Adding money to accounts is disabled
- Mangopay is still being used for payday. Money already in Mangopay wallets is being transferred to other Mangopay wallets. This payday notification as @Changaco mentions above is to let people know they need to empty out their Mangopay wallets. 
    - This could be more forcefully stated
- Stripe is set up for receive, but money is not going there yet.
- Once Stripe integration is finished, adding money will be turned back on. What this will mean is that cards will be charged and money sent to receivers' Stripe accounts immediately (on payday or when donation is set, I'm not sure). No money will be held in escrow/wallets by Liberapay.
- I am not sure what will happen to money left in Mangopay wallets. I am assuming that this money cannot be used to fund donations into Stripe accounts (and Liberapay's access to Mangopay wallets may be turned off any time). For users who have not emptied wallets when access is turned off, I assume it will be up to them to contact Mangopay to retrieve money.
    - This is something Liberapay could help with (who to contact, how)

**Pull request merged**
