### PR TITLE
Upgrade Markdown lib and allow XMPP URIs

### LINKED ISSUE #500: add support for xmpp: uri in markdown syntax
When adding and XMPP uri in the following form:
`[sat@chat.jabberfr.org](xmpp:sat@chat.jabberfr.org?join)`
the uri syntax is shown raw instead of linking to the room as expected.

### PR DESCRIPTION
**Pull request by Changaco**
Closes #500.

@EdOverflow Can you spare some time to review this? Or maybe play around with it after it's deployed? I'd appreciate any reassurance that this new code isn't leaving the door open to some XSS attacks.

### CODE REVIEW

**Comment by Changaco** [comment]
Travis is choking on the cache because of the poor dependency management of Tox.

**Comment by Changaco** [comment]
I've nuked the cache and restarted the build, it's green now.

**Comment by Changaco** [comment]
We need an extra method to filter the `src` attribute of images (and a test for that).

**Comment by Changaco** [comment]
Upstream issue: https://github.com/hoedown/hoedown/issues/209

**Comment by Changaco** [comment]
Relevant resource: [XSS Filter Evasion Cheat Sheet - OWASP](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet).

**Comment by EdOverflow** [comment]
> @EdOverflow Can you spare some time to review this? Or maybe play around with it after it's deployed? I'd appreciate any reassurance that this new code isn't leaving the door open to some XSS attacks.

Wohoo! Here comes the fun part. :)

**Comment by EdOverflow** [comment]
Here are a bunch of Markdown XSS payloads:

~~~
[a](javascript:prompt(document.cookie))
[a](j    a   v   a   s   c   r   i   p   t:prompt(document.cookie))
![a](javascript:prompt(document.cookie))\
<javascript:prompt(document.cookie)>  
<&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>  
![a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)\
[a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)
[a](&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29)
![a'"`onerror=prompt(document.cookie)](x)\
[citelol]: (javascript:prompt(document.cookie))
[notmalicious](javascript:window.onerror=alert;throw%20document.cookie)
[test](javascript://%0d%0aprompt(1))
[test](javascript://%0d%0aprompt(1);com)
~~~

**Comment by Changaco** [comment]
All of those are properly filtered and escaped. :-) I'll add them to our tests.

**Comment by EdOverflow** [comment]
Here is another fantastic resource of "naughty strings": https://github.com/minimaxir/big-list-of-naughty-strings.

**Comment by Changaco** [comment]
I've added a few more tests. Thanks @EdOverflow. :-)

**Comment by Changaco** [comment]
This is deployed. I'm seeing double escaping in link content.

**Comment by Changaco** [comment]
I've sent a proposal to move this Renderer subclass upstream: <https://github.com/FSX/misaka/issues/59>.

**Comment by Changaco** [comment]
The anti-XSS Renderer subclass has been merged upstream.

**Pull request merged**
