### PR TITLE
Add coala configuration

### PR DESCRIPTION
**Pull request by sils1297**
Run Python analysis only with `coala py-analysis` like a make target.
Install coala with the official analysis routines via:

    pip3 install coala-bears

The output of coala-ci (noninteractive human readable result dump
intended for continuoue integration) is available at
http://pastebin.com/VGHv5E7K

See https://github.com/liberapay/liberapay.com/issues/312 .

I added analysis sections only as you didn't seem to be too much interested in codestyle analysis? Semantic issue detection is indeed a problem due to your templating. I wonder if we can solve that language independently at a coala level...

### CODE REVIEW

**Comment by sils1297** [comment]
So this is duplicate code detection and complexity measurement only.

**Comment by Changaco** [comment]
I'm not opposed to code style analysis, as long as it's properly configured to not raise lots of warnings we don't care about. Nobody's ever taken the time to set that up.

**Comment by sils1297** [comment]
We can automatically reformat your code so you don't get tons fo warnings.

**Comment by Changaco** [comment]
I'd like to see a diff of the automatic changes that would be applied to our current code before agreeing to turn that feature on.

**Comment by sils1297** [comment]
Of course, coala never touches your code unless you ask it to. I can initially make a PR fixing up your Python code to PEP8 e.g. and from then one we can have GitMate comment on style violations on GitHub PRs if you want?

**Comment by Changaco** [comment]
What we need to do here is integrate coala into our Makefile so that developers and CI will use it seamlessly. I don't think we want PR comments, errors should simply show up as CI build failures.

**Comment by sils1297** [comment]
Well, right now it yields a lot of failures and thus your CI would fail. You can configure GitMate to only make a commit status for every commit and not comment on the PR, advantage here is that GitMate is smart enough to only see new issues which is hard to do in your CI because you have to run coala over several commits for that.

**Comment by sils1297** [comment]
Added codestyle commits, assuming maximum line length of 120 for python

**Comment by Changaco** [comment]
- We can drop the spacing check, we don't want to modify the files it modified.
- pep8 is making many changes we don't really want, and when it's detecting real anomalies it's not always fixing them properly. Can we tweak the configuration?

**Comment by sils1297** [comment]
Yes, we can tweak the config. coala can generate a documentation for every analysis when passed the `-B` argument: http://pastebin.com/4EmqhHev

**Comment by Changaco** [comment]
One of coala's dependencies (`language-check-0.7.6`) is currently failing to install on my machine. Also, coala is a bit heavy, and being python3-only complicates the integration into our Makefile. Maybe we should wait a while, try again later this year?

**Comment by sils1297** [comment]
Sure! coala is rather heavy ATM because it installs the full set of analyses which covers almost 40 programming languages. We have a GSoC student working on seperating it into packages so you can only take what you need after the summer.

**Comment by Changaco** [comment]
Awesome! Thanks for all your work @sils1297. I look forward to Liberapay using coala this autumn. :-)

**Comment by Changaco** [comment]
In the meantime I've made a PEP8 PR: #333.

**Pull request closed without merging**
