### PR TITLE
Fraud review

### PR DESCRIPTION
**Pull request by Changaco**
This branch brings back the UI to block payments to an account that looks fraudulent, and creates a new admin tool to facilitate fraud review.

### CODE REVIEW

**Comment by Changaco** [comment]
Screenshot of the new admin tool for fraud review

**Comment by Changaco** [comment]
Background: when Liberapay launched 3 years ago its anti-fraud mechanism was the quarantine of funds for one month, but that required holding funds in escrow and didn't fully stop fraud, so now we're moving towards a systematic review of all payment recipients.

Since Liberapay is still "neutral" we will only block payments when the user appears to be involved in fraud or another illegal activity, whereas Gratipay 2.0 had other criteria like "brand fit" when reviewing new projects.

**Comment by mattbk** [comment]
>  Gratipay 2.0 had other criteria like "brand fit" when reviewing new projects.

That was a separate process from the fraud review.

**Comment by Changaco** [comment]
I know, but the public review also resulted in payments being blocked if the project was rejected.

The point was that Liberapay will still be different from Gratipay 2.0.

**Pull request merged**
