### PR TITLE
2 typos

### PR DESCRIPTION
**Pull request by trebmuh**
Found with `codespell -q 3`

### CODE REVIEW

**Comment by Changaco** [comment]
I don't think it's a good idea to fix typos in those files, especially since they're going to be deleted in the future anyway.

**Comment by trebmuh** [comment]
> I don't think it's a good idea to fix typos in those files

Can I ask why? It's unclear for me.

**Comment by Changaco** [comment]
Like I said these files are going to be deleted anyway. Also they're not really Liberapay code, they're third party files included in the repo, so they should only be modified if it's really necessary and the modifications aren't going to cause more problems later.

**Comment by trebmuh** [comment]
That makes sense. Thank you.
Closing then.

**Pull request closed without merging**
