### PR TITLE
Expand security policy.

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by Changaco** [comment]
Screenshot after fixing the code and typos:

screen shot 2018-01-16 at 18 06 10

**Comment by Changaco** [comment]
I'm not sure that a table is the right choice, a list would be more consistent with the rest of the page and would be more compact.

I'm also not comfortable with the last two paragraphs of legalese.

**Comment by EdOverflow** [comment]
Thank you for the review, @Changaco. What in particular bothers you about those two last paragraphs?

**Comment by EdOverflow** [comment]
image

**Comment by EdOverflow** [comment]
Whoops.

**Comment by Changaco** [comment]
Uh, why are you working on a restyling? And why in this PR?

**Comment by EdOverflow** [comment]
@Changaco, long story short, I messed up. Sorry.

**Comment by EdOverflow** [comment]
@Changaco, the redesign commits were supposed to be for a separate pull request for https://github.com/liberapay/liberapay.com/issues/734.

**Comment by Changaco** [comment]
Rebased on master, and reorganized the policy.

screen shot 2018-01-18 at 13 53 05

**Comment by EdOverflow** [comment]
It looks amazing, @Changaco!

**Pull request merged**
