### PR TITLE
Clarify when transfers happen

### PR DESCRIPTION
**Pull request by mattbk**
Closes https://github.com/liberapay/liberapay.com/issues/758.

### CODE REVIEW

**Comment by mattbk** [comment]
Something like this? Or should there be more information?

**Comment by Changaco** [comment]
Only card payments are immediate. Direct debits happen 4 days later ([doc](https://docs.mangopay.com/endpoints/v2.01/payins#e281_create-a-direct-debit-web-payin)). As for bank wires we have no control over when the payment is actually initiated, it's up to the user and their bank.

Regarding the sentence you added, I'm worried it could be interpreted as "the charge will happen as soon as you select or input an amount", which isn't how this form works.

**Comment by mattbk** [comment]
Ooooh, good points.

**Comment by Changaco** [comment]
Thanks for trying @mattbk. Hopefully someday we'll find the right wording.

**Pull request closed without merging**
