### PR TITLE
Notify users who don't have any profile description

### PR DESCRIPTION
**Pull request by sjcummins**
Implemented Issue #2013 to send a notification to users without a profile description on their first payday encouraging them to add a profile description. The notification is sent at the same time as the income notification and is only sent once (first payday). The email informs them why they should add a description (suspicious/fraudulent activity) and a link to edit it. Testing includes creating users with and without profile descriptions and payment accounts and ensures those that successfully receive a payment for the first time receive the add_profile_description notification as well, and those with a description or without a payment account do not receive the notification.

### CODE REVIEW

**Review by Changaco — CHANGES_REQUESTED** [review]
- [x] The new notification should be sent to all users who have received money and don't have a profile description, not only to users who will start receiving in the future. A daily or weekly cron job would probably be more appropriate than doing this as part of payday.
- [ ] It would be better if the new notification's name was more consistent with the names of the existing notifications. It should probably be `profile_description_missing`.

**Comment by sjcummins** [comment]
For setting it up as a cron job, I'm struggling to think of an efficient way to keep track of who has already received the notification so they don't receive a new one every time it's run. Sending during the payday allowed me to use the data from the generate_income_notifications queries which made it so I only had to consider users who received income that week and never received income before that.

For what you're saying, I think I'd have to store a boolean value for each user indicating whether they already got notified, and the only way I can think of to do that is to modify the database schema. Is that the best way to do it?

**Comment by Changaco** [comment]
To determine if the notification has already been sent to a user, simply look for it in the `notifications` table.

**Comment by sjcummins** [comment]
^^ let me know if the cron job should be somewhere else; I wasn't really sure where to put it but I didn't think it should stay in payday.py

**Comment by Changaco** [comment]
You can put the cron job function with the existing ones at the end of the `liberapay/models/participant.py` file.

**Comment by sjcummins** [comment]
I think it should be good now; let me know if there’s anything else that needs to be changed.

**Comment by Changaco** [comment]
I've merged this manually because GitHub wouldn't let me force-push the branch.

**Comment by Changaco** [comment]
@sjcummins Congratulations on your first contribution, and sorry it took longer than you were hoping for.

**Comment by trebmuh** [comment]
:+1:

**Pull request closed without merging**
