### PR TITLE
Implement private and public donations

### LINKED ISSUE #271: Anonymity prevents thanking sponsors
Even if we explicitly allowed users to thank their sponsors (https://github.com/liberapay/liberapay.org/issues/12) they couldn't do it because donations are anonymous. We need to implement a way for donors to reveal their identity if they and their donees want to.

### PR DESCRIPTION
**Pull request by Changaco**
This branch will close #271. I'm hoping to complete and merge it this week, then give translators two weeks to do their work.

### CODE REVIEW

**Comment by jorgesumle** [comment]
It would be nice to write a blog post about this new feature, and share it on our long-dormant social media accounts.

I can write the blog post tonight using screenshots from this developing branch, so that you have time to review it before publishing it.

**Comment by trebmuh** [comment]
Nice to see this feature coming.
Agreed with @jorgesumle : this feature deserves to have a communication package along with it.

**Comment by Changaco** [comment]
There will be a blog post of course. I was planning to write it myself as usual, but you can try to do it if you want to, @jorgesumle.

**Comment by jorgesumle** [comment]
## Users can now thank their sponsors

We are happy to announce that users can now allow non-anonymous donations. What do we mean? Donations in Liberapay were anonymous until now, so users could not thank their sponsors. By adding this feature we hope that donators can now be credited for their contribution.

If you are a creator who wants to allow donators reveal their identity to you and to the public, you should activate this new feature in the **Receiving>Patrons** menu...

enable_non-anonymous_donations

When you activate this feature, you will see something like this:

Captura de ecrã de 2021-11-15 21-58-23

With this feature enabled users will be able to select a privacy level in the donation form:

Captura de ecrã de 2021-11-15 22-00-35

**Comment by jorgesumle** [comment]
I believe that the following code should be added to `/templates/layouts/components/navbar-logged-in.html`:
```
<li class="level2"><a href="/{{ user.username }}/patrons/">{{ _("Patrons") }}</a></li>
```

I don't have much time right now to write a proper blog post, but the comment and the images above can be useful to get you started. We should also show the list of patrons. I didn't have time to connect the payment account and play with fake users to show this. @Changaco, can you finish my work? I can help review it before publishing.

It would be nice to figure #136 out. We could also post it in Spanish, French, etc., and reach more people, and under something like `https://blog.liberapay.com` for better SEO than with Medium.

**Comment by Changaco** [comment]
The last two weeks have been more busy than expected, so I'm a little late on this, but everything should be ready tomorrow. The blog post is almost complete, here's the link to the draft: https://medium.com/@liberapay/lifting-the-veil-of-anonymity-479dadd369be

**Comment by Changaco** [comment]
The deployment is done. Any feedback on the blog post draft before I publish it?

**Comment by jorgesumle** [comment]
> Any feedback on the blog post draft before I publish it?

Sure!

> , If you don’t want to publish the amounts of your donations, then: go

The colon is incorrect there, it should only be used "to introduce a list when the introductory phrase is an **independent clause**" (not in conditional sentences or dependent clauses). Also, the "then" in conditional sentences can be omitted if you want.

> However, these lists probably won’t contain any names at the beginning, because your donors won’t have opted-in and input their public names yet.

This sentence sounds overly complicated to me. I would rewrite it to: "these lists will be empty until your donors opt-in and input their public names".

> any new donor will be asked to choose a visibility level for their donation.

I'd say "new donors" instead of "any new donor" here.

> In the near future, it will become possible

I'd say "it will **be** possible". I think "become possible" is incorrect.

**Comment by Changaco** [comment]
Thanks. I've made some cosmetic changes.

> This sentence sounds overly complicated to me. I would rewrite it to "these lists will be empty until your donors opt-in and input their public names".

Not containing names isn't the same thing as being empty.

**Comment by jorgesumle** [comment]
> Not containing names isn't the same thing as being empty.

"these lists won't have any name until your donors opt-in and input them".

**Comment by Changaco** [comment]
I've rewritten the sentence in a very different way, and published the blog post.

**Comment by trebmuh** [comment]
Nice to see this feature coming in, congratz!

**Comment by Changaco** [comment]
So far 354 creators have opted-in to see who their donors are, and 84 have opted-out.

<details>

```sql
SELECT value, count(*)
  FROM ( SELECT DISTINCT ON (participant)
                payload->>'patron_visibilities' AS value
           FROM events
          WHERE type = 'recipient_settings'
            AND payload ? 'patron_visibilities'
       ORDER BY participant, ts DESC
       ) x
 GROUP BY value;
 value | count 
-------+-------
 1     |    84
 7     |   354
(2 rows)
```

</details>

**Pull request merged**
