### PR TITLE
Fix :fr: translation for the login message

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by trebmuh** [comment]
Thanks for pointing it.
@Changaco : I made the fix in Weblate.

**Comment by Changaco** [comment]
I've merged this so that the Git history will accurately reflect who detected this typo and submitted a fix for it.

**Comment by trebmuh** [comment]
There won't be any conflict with the change I've made?

**Comment by Changaco** [comment]
@trebmuh I discarded your change when I merged the changes from Weblate, then I merged this commit.

**Comment by trebmuh** [comment]
OK. I was understanding that I was still referenced on this one on Weblate (https://hosted.weblate.org/translate/liberapay/core/fr/?q=identifier) but you probably understand Weblate better than I do, so all is good!

**Pull request merged**
