### PR TITLE
Implement rate limiting

### LINKED ISSUE #478: Sign-ups aren't throttled
Someone targeted a form-posting bot at liberapay.com, which resulted in several sentry errors (#477) and many fake accounts being created:

spectacle m18037

Those requests probably all came from a single IP address (we don't log them so I can't check directly).

### LINKED ISSUE #495: Authentication attempts aren't rate-limited
Rate-limiting helps prevent timing attacks (<https://github.com/liberapay/liberapay.com/pull/489>), brute force, denials of service, and other nuisances (e.g. <https://github.com/liberapay/liberapay.com/issues/478>).

### PR DESCRIPTION
**Pull request by Changaco**
This branch implements half of #658 and half of #61, closes #478, and also closes #495.

The proposed rate limits are:

- for verification emails (when a new account is created or an email address is added to an existing account): 5 per day per user, 2 per day per email address
- for email logins: 10 per day per user, 2 per day per unverified email address
- for password logins: 3 per hour per user
- for account creations: 5 per hour per IP address, 15 per 15 minutes per IP network (/16 for IPv4, /32 for IPv6), 15 per 15 minutes per IP version (IPv4 or IPv6)

The hardest part for the account creation rate limits was actually determining the IP address of the request in a reliable way. I ended up implementing the logic in the python app (could be moved upstream to Pando).

Ping @EdOverflow since this is about protecting Liberapay from DoS attacks (and other people from email spam).

Remaining TODO:

- in #658: move the rate limiter to a separate project so others can use it
- in #61: implement an email address blacklist so people being spammed can immediately stop the influx of emails

### CODE REVIEW

**Comment by Changaco** [comment]
I've created an issue about moving stuff upstream into Pando: <https://github.com/AspenWeb/pando.py/issues/581>.

**Comment by EdOverflow** [comment]
@Changaco: I am currently reviewing this PR. Are you able to access Gratipay's HackerOne inbox?

**Comment by Changaco** [comment]
@EdOverflow No. I remember proposing to help with Gratipay's HackerOne a while back, but I wasn't given access.

**Comment by Changaco** [comment]
If there is no concrete feedback I'm going to merge this soon.

**Comment by Changaco** [comment]
Rebased on master. Will merge once Travis is green.

**Comment by Changaco** [comment]
This is now deployed.

**Pull request merged**
