### PR TITLE
Improve accessibility

### PR DESCRIPTION
**Pull request by Changaco**
This branch fixes a bunch of issues, including #967, #1774, #1775 and #1776.

### CODE REVIEW

**Comment by rkingett** [comment]
Is there any way the below can be done without using ARIA? ARIA should never be used if it can be achieved natively.

> add an extra ARIA label to subnav checkboxes

Could you do this natively without ARIA?

**Comment by Changaco** [comment]
I guess it's technically possible to add a second `<label>` specifically for screen readers, instead of an `aria-label` attribute on the checkbox, but would that really be any better? I don't think so.

These checkboxes aren't visible on screen, their purpose is to provide a toggling mechanism based on CSS instead of JavaScript.

**Comment by rkingett** [comment]
Gotcha! I thought they were visible on screen. On second thought, ARIA would work in this particular instance.

**Comment by Changaco** [comment]
These changes are now deployed. @rkingett If the result is unsatisfactory, or if you find other problems, you can of course open new issues.

**Pull request merged**
