### PR TITLE
Change view to ansicht

### PR DESCRIPTION
**Pull request by ltsavar**

### CODE REVIEW

**Comment by Changaco** [comment]
Thank you for contributing, but can you resubmit this change [on Weblate](https://hosted.weblate.org/projects/liberapay/core/de/)? If I merge this here it may create a Git conflict the next time I try to pull in the new translations from Weblate.

**Comment by ltsavar** [comment]
Sure. 
I ve no rights to save. So i did a suggestions.

https://hosted.weblate.org/translate/liberapay/core/de/?type=suggestions

**Comment by Changaco** [comment]
@ltsavar Anyone can save, you just have to create an account and log in first. 😉

**Comment by ltsavar** [comment]
I used my github account for weblate. so i was logged in before :)
Now i could save the translation. Don't know what changed.
So its done :)

**Pull request closed without merging**
