### PR TITLE
More pledges

### PR DESCRIPTION
**Pull request by Changaco**
We haven't been doing a good job at telling users that they can pledge to people who haven't joined Liberapay yet. This PR allows us to see who other users are pledging to, and advertises pledging on the homepage.

### CODE REVIEW

**Comment by Changaco** [comment]
Screenshot of the new Explore Pledges page:

liberapay-2016-02-17-explore-pledges

**Comment by MartinDelille** [comment]
> Liberapay allows you to pledge to donate to people...

I'm not a native english speaker but there is a repetition here, isn't it a problem?

**Comment by Changaco** [comment]
It is a lot of "to"s in one sentence and should probably be reworded. However this message is just copy-pasted from another page, it's not being added by this PR, and if we change it we have to update the translations. Moreover, "pledge to donate" is not exactly a repetition: "pledge" means "promise", if we don't say what's being promised then the sentence is slightly ambiguous.

**Comment by Changaco** [comment]
This is deployed. Now let's make some pledges, because right now https://liberapay.com/explore/pledges/ is empty!

**Pull request merged**
