### PR TITLE
add share button to profil fix #49

### LINKED ISSUE #49: Add share buttons to profiles
Diaspora*, Facebook, Google+, Twitter… Simple links with self-served logos like on [this site](https://opelections.oy.lc/), not widgets that would allow the sites to track Liberapay users.

### PR DESCRIPTION
**Pull request by MartinDelille**
This is my first code contribution. There might be some fix to apply before merging so don't hesitate to comment.

I linked the CDN to [font awesome](https://fortawesome.github.io/Font-Awesome/) because I was unable to find how adding CSS library like you did for bootstrap.

There is no pre-filled text because it doesn't work for facebook and google+ API.

### CODE REVIEW

**Comment by Changaco** [comment]
> I was unable to find how adding CSS library like you did for bootstrap

It's pretty simple: the files are in the `www/assets/` directory. `website.asset('bootstrap/...')` returns an `/assets/bootstrap/...` path, and the files are read from `www/assets/bootstrap/...` by Aspen when requested.

So, just download fontawesome into `www/assets/`, `git add` them (only the files we actually need, e.g. not the non-minified versions), then replace `https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css` with `{{ website.asset('font-awesome/4.5.0/css/font-awesome.min.css') }}`.

**Comment by MartinDelille** [comment]
The font awesome need several files and has reference to *../fonts* folder so I put it in a *css* folder. Maybe we should put other css file there?

**Comment by Changaco** [comment]
I think we should put fontawesome in its own directory (and a version subdirectory), like bootstrap. `www/assets/fontawesome/4.5.0/{css,fonts}`

**Comment by Changaco** [comment]
Also, please rebase PRs on master instead of merging master into them, the history is cleaner that way.

**Comment by MartinDelille** [comment]
Ok for the directory.
Do you want me to squash the commits?

**Comment by Changaco** [comment]
Whether to squash the commits or not is up to you.

**Comment by MartinDelille** [comment]
Done :-)

**Comment by Changaco** [comment]
Looks like Travis missed the commit, again. I suggest a `git commit --amend --no-edit && git push -f`.

**Comment by Changaco** [comment]
Okay, we're good, but what does it actually look like? A screenshot is useful for this kind of PR. ;-)

**Comment by MartinDelille** [comment]
capture d ecran 2016-02-07 22 38 13

**Comment by Changaco** [comment]
The links are taking too much space, they'll make the box longer if you set a funding goal (because that adds a progress bar). I think we want to put them on the bottom-right of box, either inside it or just below. We can shorten the text to simply "Share:", and put it on the same line as the buttons instead of above them.

**Comment by MartinDelille** [comment]
Hi @Changaco, sorry I've been very busy this week but I will finish that maybe in the week-end. I was facing a problem to display the local environment: how can I display the funding goal?
- I can't validate my email on my local account (I guess sending mail doesn't work in local)
- I check several populated profil but none of them have a funding goal
Solving one of these two problem could help me going on.

**Comment by MartinDelille** [comment]
Another question about layout: it seems that currently we only use bootstrap css class right? no custom styling? (I guess I don't need custom css anyway)

**Comment by Changaco** [comment]
> sorry I've been very busy this week

No need to apologize. :-) If I was blocked by this PR I would have completed it myself. ;-)

> I can't validate my email on my local account (I guess sending mail doesn't work in local)

We use Mandrill for emails, but the default key is a test key that doesn't actually send the emails. In #149 (https://github.com/liberapay/liberapay.com/commit/831941468e28f951bab78b4da2e141ec759e2711) I added printing of emails to stdout to ease development, so if you go to your emails page and click the "Resend" button you'll see the verification link in the console. Previously you add to manually build the verification link by getting the token from the DB if you wanted to verify an email address locally.

> I check several populated profil but none of them have a funding goal

You mean profiles of fake users (those created by `make data`), right? You can simply add a funding goal to your local account by editing its profile.

> it seems that currently we only use bootstrap css class right? no custom styling?

We do have some custom styles, they're in `style/base/base.scss`.

**Comment by MartinDelille** [comment]
Here is the screen capture:
capture d ecran 2016-02-14 18 42 09
I'm far to be a CSS wizard so I tried to keep it as simple as possible.

**Comment by Changaco** [comment]
I've moved the buttons below the box, and fixed the mismatched tag (`<p>...</div>`).

spectacle tj7855

**Comment by MartinDelille** [comment]
This is in fact much better.

**Comment by Changaco** [comment]
:-) !m @MartinDelille

**Pull request merged**
