### PR TITLE
Logos

### LINKED ISSUE #1425: Press kit for creators?
I'd like to promote my Liberapay profile on YouTube - I couldn't find an official "press kit" or "brand guidelines" - I think it's a good thing to develop this to help popularize Liberapay.

I have downloaded the Liberapay logo in SVG from the main page, though it'd be good to have this explicitly available somewhere in a ZIP. I'm a graphic designer so  I can handles this myself, but others might not be so lucky, and might need a PNG, JPG version etc...

What do you think?

### PR DESCRIPTION
**Pull request by Changaco**
This branch will fix #1425.

I've had this WIP commit in a local branch since September 2017, maybe putting it here will motivate me or someone else to complete it.

### CODE REVIEW

**Comment by MartinDelille** [comment]
What do you think of this first draft?

Capture d'écran 2019-03-13 00 19 38

**Comment by Changaco** [comment]
It's a good start. Improvement ideas:

- [ ] reword the intro paragraph to be more generic (the new page isn't specifically meant for users who want to advertise their profiles, it's also for the press, for partners, etc.)
- [ ] specify what the ZIP files contain (what the image formats and sizes are)
- [ ] add the wide black-on-yellow logo that we use for stickers and on Facebook
- [ ] add legal information (copyright and trademark)
- [ ] add a link to https://github.com/liberapay/liberapay.com/tree/master/www/assets/liberapay as an alternative way of browsing and downloading the files

**Comment by MartinDelille** [comment]
> add the wide black-on-yellow logo that we use for stickers and on Facebook

Do we have the original SVG of this file?

**Comment by MartinDelille** [comment]
I implemented most of your suggestion. Here is a new screenshot:
Screenshot 2019-03-14 21 29 24

**Comment by Changaco** [comment]
> Do we have the original SVG of this file?

Yes. I've added the SVG as well as the PNG used on Facebook (1024px).

**Comment by Changaco** [comment]
Screenshot of the new and completed Logos page

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
