### PR TITLE
Wording in the FAQ

### PR DESCRIPTION
**Pull request by trebmuh**
It sounds unusual when using a singular form in the first part, then a plural form in the second part.
Suggestion is to keep it consistent across the sentence.
Then there are 2 possibilities:
1) all singular,
2) all plural.

I choose the singular form to keep it light.

### CODE REVIEW

**Comment by Changaco** [comment]
"they" is not plural here, it's a gender-neutral singular.

**Comment by Changaco** [comment]
https://en.wiktionary.org/wiki/they

**Comment by trebmuh** [comment]
Quoting from wikipedia:

> usually plural, sometimes singular

It's confusing. My guestimate is that most people (specially the non-English native like me) are expecting they to reflect plural.

**Comment by trebmuh** [comment]
Alternate wording, less confusing IMHO:

> When a user connects an external account (for example a {platform1} or {platform2} account) to a Liberapay profile, that automatically proves that this user controls this account.

**Comment by mattbk** [comment]
The alternate wording works for me. Conversely, you could write something like
> Control of a Liberapay account is automatically proven by connection of one or more external accounts (for example a {platform1} or {platform2} account).

**Comment by jorgesumle** [comment]
@trebmuh, I was confused until I learnt about it.

> It's confusing. My guestimate is that most people (specially the non-English native like me) are expecting they to reflect plural.

I wouldn't change it unless native English-speakers would complain about it. @mattbk, does it look correct to you?

**Comment by mattbk** [comment]
I'm a traditionalist in that I expect "they" to be plural, so I may not be much help. It jumps out to me, but someone younger than I or who has less experience with formal writing may not even notice the issue being pointed out here.

**Comment by trebmuh** [comment]
@Changaco @mattbk @jorgesumle : I was pretty much out of the web with a full-time training on the last weeks. I've PR @mattbk 's proposition which sounds clearer to me.

If you do agree, please merge.

**Comment by jorgesumle** [comment]
I think that you need to put a comma after "for example".

**Comment by trebmuh** [comment]
Good catch. Done.

**Comment by Changaco** [comment]
@jorgesumle You should not have merged this, and especially not with a merge commit. An atomic 3-line change should be a single commit, not 5!

**Pull request merged**
