### PR TITLE
Start using a brand color

### LINKED ISSUE #281: Brand color
To achieve #183 and complete #278 we need to decide on a brand color.

We've been using some red for our [widgets](https://github.com/liberapay/liberapay.com/blob/82/www/assets/widgets/donate.svg.spt) and on [Twitter](https://twitter.com/liberapaye), but it is relatively close to [Tipeee](https://twitter.com/tipeee_officiel)'s red/pink.

### PR DESCRIPTION
**Pull request by Changaco**
This PR will close #281.

### CODE REVIEW

**Comment by Changaco** [comment]
TODO:

- [ ] update widgets
- [ ] customize Bootstrap's `brand-*` colors https://getbootstrap.com/customize/

**Comment by Changaco** [comment]
Screenshot of the widgets page:

liberapay-2016-05-20-widgets

**Comment by Changaco** [comment]
I've added a commit to modify the "Donate" buttons around the site, screenshots below.

Top of a profile page:

liberapay-2016-05-21-profile-page

---

Donate page:

liberapay-2016-05-21-donate-page

---

A few pledges (`/on/twitter/` page):

liberapay-2016-05-21-pledges

**Comment by Changaco** [comment]
I don't have time to customize Bootstrap's colors, I'm merging this as it is.

**Comment by MartinDelille** [comment]
I'll be happy to try some color scheme with the new brand color. Basically, it seems we need to add a `config.json` file, but I don't understand well how bootstrap is used.

I understood that we need to serve the `config.json` file at the root of the bootstrap root, am I right?

**Comment by MartinDelille** [comment]
@Changaco ?

**Pull request merged**
