### PR TITLE
Redesign profile page

### LINKED ISSUE #608: Design improvement
I would like to contribute to Liberapay. I don't know Python very well, I would like to help on the front-end. I started a little redesign of the team page.

screen shot 2017-06-07 at 23 09 46-fullpage

I would like to have your opinion on this, and see how I could contribute (even if it's not by making style changes, I saw there is many "UI" issues I could work on).

Thanks for your feedback!

### PR DESCRIPTION
**Pull request by Bat41**
Fixes #608 

It's not exactly the same as the mockup I did, but it is still very similar. Here is how it looks like.

screen shot 2017-10-10 at 17 24 51-fullpage

I also changed the font to Open Sans. I don't know if it's fine, or if we should stick to Ubuntu.

### CODE REVIEW

**Comment by Changaco** [comment]
Nice work. I'll look at it more closely tomorrow.

**Comment by trebmuh** [comment]
Nice looking 👍

**Comment by Changaco** [comment]
Ready for review. I've made quite a few changes…

**Comment by Changaco** [comment]
Screenshots:

liberapay-2017-10-13-profile-changaco

---

liberapay-2017-10-13-profile-liberapay

---

liberapay-2017-10-13-profile-changaco-375p

---

liberapay-2017-10-13-profile-liberapay-375p

**Comment by aloisdg** [comment]
Nice work!

**Comment by Changaco** [comment]
Sneaked in a fix for #732.

**Comment by trebmuh** [comment]
Looks really good to me.

**Pull request merged**
