### PR TITLE
Refresh the user interface icons, add card brand logos

### LINKED ISSUE #2117: Icons of linked accounts do not have text as backup
When the icon font won't load, it looks like this:
image

Source: https://liberapay.com/timokoesters

### LINKED ISSUE #2309: Update Twitter logo to X
The Twitter logo/name appears in multiple parts of the website, such as the navbar7footer and when linking accounts.

### PR DESCRIPTION
**Pull request by Changaco**
- Drop icon fonts (Glyphicons and Forkawesome). Add SVGs from [Bootstrap Icons](https://icons.getbootstrap.com/) as replacements. (See [Inline SVG vs Icon Fonts](https://css-tricks.com/icon-fonts-vs-svg/) and [Stop Using Icon Fonts](https://www.irigoyen.dev/blog/2021/02/17/stop-using-icon-fonts/) for the reasons to drop icon fonts.)
- Add logos of payment card brands and use them in the payment method selection page.
- Refresh the icons of social platforms, optimize them, and give them text labels. (Closes #2117. Closes #2309.)

### CODE REVIEW

**Comment by Changaco** [comment]
Screenshot showing the added card brand icons

---

Screenshot of the refreshed icons of social platforms

**Comment by Changaco** [comment]
Loading the Liberapay front page currently requires downloading 240.88 kB of data. The changes in this branch should cut that number almost in half.

**Comment by iacore** [comment]
Thanks for your work.
The icon vertical alignment is off. How do I contribute?

**Comment by Changaco** [comment]
@iacore You were still looking at the old icons. The new ones have now been deployed.

All the instructions on contributing are in the README. If you'd like to contribute on CSS issues, Liberapay needs to be updated from Bootstrap v3 to v5: #940.

There is currently no way to run Liberapay without a PostgreSQL database.

**Comment by iacore** [comment]
some new icons are not vertically aligned

image

**Comment by Changaco** [comment]
The icons are vertically centered. The alignment doesn't look as good as in other places because in these buttons the text is larger than the icon (20px vs 16px). I tested scaling the icons to match the text but I didn't really like it better.

**Comment by iacore** [comment]
On some Zoom levels, this icon is clipped.

image

**Comment by Changaco** [comment]
> Loading the Liberapay front page currently requires downloading 240.88 kB of data. The changes in this branch should cut that number almost in half.

Actual result: 128.39 kB.

**Comment by iacore** [comment]
> It looks like the browser is incorrectly scaling the SVG. There doesn't seem to be any way to work around this bug.

The SVG need to larger than the icon. Currently the SVG are exactly, as large as the icon (the visible part).

**Comment by Changaco** [comment]
Increasing the height and width of the SVG view box by one unit does eliminate the scaling overflow.

**Pull request merged**
