### PR TITLE
Little Change

### PR DESCRIPTION
**Pull request by taufiqsumadi**
i found Missing '{', '}'.

### CODE REVIEW

**Comment by Changaco** [comment]
Thanks. The proper way to contribute to translations is through <https://hosted.weblate.org/projects/liberapay/core/>, but exceptionally I'll merge this PR.

**Comment by Changaco** [comment]
@taufiqsumadi Would you like to join [the Liberapay team](https://liberapay.com/Liberapay/) as a translator?

**Comment by taufiqsumadi** [comment]
But you must pay me expensively :smiley: @Changaco haha, ok i want :smile:

**Comment by Changaco** [comment]
@taufiqsumadi I need your Liberapay username to add you to the team, if you don't have an account yet then [sign up](https://liberapay.com/sign-up).

**Comment by taufiqsumadi** [comment]
username liberapay: taufiqsumadi
@Changaco

**Comment by Changaco** [comment]
Invite sent.

**Comment by Changaco** [comment]
@taufiqsumadi You should read https://github.com/liberapay/salon/issues/13 and subscribe to it. Welcome aboard. :-)

**Pull request merged**
