### PR TITLE
Tweak the income notification wording

### PR DESCRIPTION
**Pull request by Changaco**
Is it any clearer?

### CODE REVIEW

**Comment by trebmuh** [comment]
Can you explain the difference between "for" and "during" (e.g. within an asterisk)?

**Comment by Changaco** [comment]
Well, that answers my question: it's not clearer.

**Comment by trebmuh** [comment]
Correct. The hard part here I guess is to make the information clear from an user point of view. Probably the information you want to write here is clear in your brain because you wrote the code. But it's still not from an user POV. Probably a couple of sentences will be needed here to make it crystal clear.

**Comment by Changaco** [comment]
The paragraph I was trying to fix in my first commit isn't the real problem, it's the one below mentioning the Mangopay wallet balance that generates the most confusion.

**Pull request closed without merging**
