### PR TITLE
Monthly and yearly income totals

### PR DESCRIPTION
**Pull request by Changaco**
This branch adds monthly and yearly income and spending totals to the Ledger page.

### CODE REVIEW

**Comment by trebmuh** [comment]
Nice addition :+1:

**Comment by trebmuh** [comment]
Anyway to separate by payment processors? Such as
* with Paypal : monthly XX€ and YY$
* with Strip : monthly XX€ and YY$
* with Mangopay : monthly XX€ and YY$
_(and the same with yearly)_

**Comment by mattbk** [comment]
> Anyway to separate by payment processors? Such as

This would help with accounting and so people could see easily which payment processor is most useful for them.

**Comment by Changaco** [comment]
Rebased on master and added a warning about misleading totals.

**Comment by Changaco** [comment]
I'll look into splitting by payment processor next time.

**Comment by trebmuh** [comment]
I've opened an issue for keeping track of it.

**Pull request merged**
